# https://numtide.github.io/devshell
[[commands]]
category = "formatting"
package = "treefmt"

[[commands]]
category = "formatting"
package = "nixpkgs-fmt"

[[commands]]
category = "formatting"
package = "taplo"

[devshell]
packages = ["rnix-lsp", "vscode"]
