name: nix-flake-check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Configure Cachix caches
        uses: cachix/cachix-action@v12
        with:
          name: mevensson-nixos-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nrdxp,nix-community

      - name: Check Flake
        run: nix flake check --show-trace
